"""Add name and created_at to CV model

Revision ID: 54d0321aa26d
Revises: 3f474892a3df
Create Date: 2024-09-28 22:23:00.785122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d0321aa26d'
down_revision = '3f474892a3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=True))
    
    # Set default values for existing rows
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE cv
        SET created_at = CURRENT_TIMESTAMP,
            name = 'CV ' || id
        WHERE created_at IS NULL
    """))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
