"""Add Token model

Revision ID: 559eda59a405
Revises: 6ae738ae26e0
Create Date: 2024-10-23 15:42:05.874788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559eda59a405'
down_revision = '6ae738ae26e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###
